export const KID_POOL_SIZE = 200;
export const ADULT_POOL_SIZE = 1143;
export const WORD_BANK = [
  "apple", "banana", "orange", "grape", "mango", "peach", "lemon", "melon", "berry", "pear",
  "cat", "dog", "bird", "fish", "frog", "duck", "lion", "tiger", "zebra", "horse",
  "cow", "goat", "sheep", "mouse", "rabbit", "monkey", "panda", "koala", "whale", "shark",
  "red", "blue", "green", "yellow", "gold", "purple", "pink", "brown", "black", "white",
  "sun", "moon", "star", "cloud", "rain", "snow", "wind", "storm", "sky", "light",
  "book", "pen", "pencil", "paper", "chair", "table", "clock", "phone", "bag", "shoe",
  "shirt", "pants", "socks", "hat", "coat", "dress", "bed", "door", "window", "house",
  "car", "bus", "train", "plane", "boat", "bike", "road", "park", "school", "store",
  "happy", "sad", "angry", "smile", "laugh", "jump", "run", "walk", "dance", "sing",
  "yes", "no", "hello", "thank", "please", "sorry", "water", "milk", "bread", "rice",
  "ant", "bee", "bug", "fly", "worm", "snake", "turtle", "owl", "eagle", "hawk",
  "crow", "swan", "goose", "hen", "rooster", "pig", "hamster", "guinea", "pet", "farm",
  "barn", "field", "river", "lake", "ocean", "beach", "sand", "shell", "coral", "reef",
  "island", "volcano", "forest", "tree", "leaf", "root", "seed", "flower", "grass", "weed",
  "bush", "vine", "oak", "pine", "maple", "cedar", "palm", "cactus", "desert", "oasis",
  "meadow", "valley", "canyon", "cliff", "cave", "hill", "mountain", "peak", "glacier", "ice",
  "frost", "dew", "mist", "fog", "steam", "heat", "cold", "warm", "cool", "breeze",
  "gust", "hurricane", "tornado", "earthquake", "thunder", "lightning", "bolt", "rainbow", "dawn", "dusk",
  "noon", "midnight", "evening", "morning", "afternoon", "tonight", "today", "tomorrow", "yesterday", "week",
  "month", "year", "season", "spring", "summer", "autumn", "winter", "holiday", "birthday", "party",
  "gift", "toy", "doll", "ball", "kite", "balloon", "puzzle", "block", "robot", "rocket",
  "alien", "planet", "comet", "meteor", "space", "astronaut", "pilot", "sailor", "captain", "pirate",
  "treasure", "map", "compass", "anchor", "harbor", "dock", "bridge", "tunnel", "station", "airport",
  "hotel", "museum", "library", "theater", "cinema", "music", "song", "drum", "flute", "guitar",
  "piano", "violin", "trumpet", "horn", "whistle", "bell", "alarm", "watch", "calendar", "diary",
  "letter", "stamp", "envelope", "package", "basket", "bucket", "bowl", "plate", "spoon", "fork",
  "knife", "cup", "mug", "bottle", "jar", "box", "pack", "suitcase", "wallet", "coin",
  "dollar", "cent", "price", "shop", "market", "mall", "bakery", "butcher", "cafe", "diner",
  "kitchen", "oven", "stove", "fridge", "freezer", "sink", "tap", "shower", "bath", "towel",
  "soap", "brush", "comb", "mirror", "lamp", "candle", "torch", "battery", "wire", "plug",
  "socket", "screen", "keyboard", "cable", "internet", "email", "website", "video", "photo", "camera",
  "picture", "frame", "statue", "painting", "canvas", "ink", "paint", "color", "crayon", "marker",
  "chalk", "board", "eraser", "ruler", "scissors", "tape", "glue", "paperclip", "staple", "pin",
  "needle", "thread", "button", "zipper", "pocket", "belt", "glove", "scarf", "ribbon", "lace",
  "wool", "cotton", "silk", "leather", "wood", "metal", "steel", "iron", "copper", "brass",
  "silver", "jewel", "ring", "necklace", "bracelet", "earring", "crown", "sword", "shield", "castle",
  "knight", "dragon", "wizard", "witch", "magic", "spell", "potion", "crystal", "maze", "labyrinth",
  "riddle", "trophy", "medal", "badge", "sticker", "tattoo", "seal", "sign", "symbol", "arrow",
  "circle", "square", "triangle", "diamond", "heart", "spade", "club", "chess", "checkers", "domino",
  "dice", "poker", "bingo", "lottery", "ticket", "coupon", "prize", "reward", "bonus", "level",
  "score", "record", "champion", "winner", "loser", "player", "team", "coach", "referee", "stadium",
  "arena", "gym", "yoga", "ballet", "karate", "judo", "boxing", "wrestling", "fencing", "archery",
  "bowling", "golf", "tennis", "soccer", "rugby", "hockey", "baseball", "cricket", "volleyball", "badminton",
  "squash", "racket", "net", "goal", "post", "jersey", "helmet", "pads", "uniform", "boots",
  "cleats", "skate", "ski", "sled", "surf", "dive", "swim", "float", "lifejacket", "sail",
  "mast", "oar", "paddle", "canoe", "kayak", "raft", "ferry", "cruise", "submarine", "tanker",
  "cargo", "truck", "van", "jeep", "wagon", "tractor", "bulldozer", "crane", "forklift", "elevator",
  "escalator", "subway", "tram", "cablecar", "monorail", "highway", "traffic", "signal", "crosswalk", "sidewalk",
  "alley", "avenue", "boulevard", "district", "neighborhood", "village", "town", "city", "capital", "province",
  "state", "nation", "border", "passport", "visa", "journey", "voyage", "trip", "tour", "guide",
  "across", "action", "activity", "actor", "actress", "add", "address", "adult", "advice", "afraid",
  "age", "ago", "agree", "air", "also", "always", "amazing", "animal", "another", "answer",
  "anyone", "anything", "apartment", "april", "area", "arm", "around", "arrive", "art", "article",
  "artist", "ask", "august", "aunt", "away", "baby", "back", "bad", "band", "bank",
  "bathroom", "beautiful", "become", "bedroom", "beer", "begin", "beginning", "behind", "believe", "best",
  "better", "bicycle", "big", "bill", "blog", "blonde", "body", "boot", "bored", "boring",
  "born", "boy", "boyfriend", "break", "breakfast", "bring", "brother", "build", "building", "business",
  "busy", "butter", "buy", "bye", "cake", "call", "cannot", "card", "career", "carrot",
  "carry", "cd", "centre", "century", "change", "chart", "cheap", "check", "cheese", "chicken",
  "child", "chocolate", "choose", "class", "classroom", "clean", "climb", "close", "clothes", "coffee",
  "college", "colour", "come", "common", "company", "compare", "complete", "computer", "concert", "conversation",
  "cook", "cooking", "correct", "cost", "country", "course", "cousin", "cream", "create", "culture",
  "customer", "cut", "dad", "dancer", "dancing", "dangerous", "dark", "date", "daughter", "day",
  "dear", "december", "decide", "delicious", "describe", "description", "design", "desk", "detail", "dialogue",
  "dictionary", "die", "diet", "difference", "different", "difficult", "dinner", "dirty", "discuss", "dish",
  "doctor", "downstairs", "draw", "drink", "drive", "driver", "dvd", "ear", "early", "east",
  "easy", "eat", "egg", "eight", "eighteen", "eighty", "elephant", "eleven", "else", "end",
  "enjoy", "enough", "euro", "even", "event", "ever", "every", "everybody", "everyone", "everything",
  "exam", "example", "excited", "exciting", "exercise", "expensive", "explain", "extra", "eye", "face",
  "fact", "fall", "false", "family", "famous", "fantastic", "far", "farmer", "fast", "fat",
  "father", "favourite", "february", "feel", "feeling", "festival", "fifteen", "fifth", "fifty", "fill",
  "film", "final", "find", "fine", "finish", "fire", "first", "five", "flat", "flight",
  "floor", "follow", "food", "foot", "football", "forget", "form", "forty", "four", "fourteen",
  "fourth", "free", "friday", "friend", "friendly", "front", "fruit", "full", "fun", "funny",
  "future", "game", "garden", "geography", "get", "girl", "girlfriend", "give", "glass", "go",
  "good", "goodbye", "grandfather", "grandmother", "grandparent", "great", "grey", "group", "grow", "guess",
  "hair", "half", "hand", "happen", "hard", "hate", "head", "health", "healthy", "hear",
  "help", "hey", "hi", "high", "history", "hobby", "home", "homework", "hope", "hospital",
  "hot", "hour", "however", "hundred", "hungry", "husband", "idea", "imagine", "important", "improve",
  "include", "information", "interest", "interested", "interesting", "interview", "introduce", "jacket", "january", "jeans",
  "job", "join", "juice", "july", "june", "keep", "key", "kilometre", "kind", "know",
  "land", "language", "large", "last", "late", "later", "learn", "leave", "left", "leg",
  "lesson", "let", "lie", "life", "line", "list", "listen", "little", "live", "local",
  "long", "look", "lose", "lot", "love", "lunch", "machine", "magazine", "main", "make",
  "man", "many", "march", "married", "match", "may", "maybe", "meal", "mean", "meaning",
  "meat", "meet", "meeting", "member", "menu", "message", "metre", "mile", "million", "minute",
  "miss", "mistake", "model", "modern", "moment", "monday", "money", "mother", "mouth", "move",
  "movie", "much", "mum", "must", "name", "natural", "near", "need", "negative", "neighbour",
  "never", "new", "news", "newspaper", "next", "nice", "night", "nine", "nineteen", "ninety",
  "nobody", "north", "nose", "note", "nothing", "november", "number", "nurse", "object", "october",
  "office", "often", "oh", "ok", "old", "one", "onion", "online", "open", "opinion",
  "opposite", "order", "outside", "page", "pair", "paragraph", "parent", "part", "partner", "past",
  "pay", "people", "pepper", "perfect", "period", "person", "personal", "photograph", "phrase", "piece",
  "place", "plan", "plant", "play", "point", "police", "policeman", "pool", "poor", "popular",
  "positive", "possible", "potato", "pound", "practice", "practise", "prefer", "prepare", "present", "pretty",
  "probably", "problem", "product", "programme", "project", "put", "quarter", "question", "quick", "quickly",
  "quiet", "quite", "radio", "read", "reader", "reading", "ready", "real", "really", "reason",
  "relax", "remember", "repeat", "report", "restaurant", "result", "return", "rich", "ride", "right",
  "room", "routine", "rule", "salad", "salt", "sandwich", "saturday", "say", "science", "scientist",
  "sea", "second", "section", "see", "sell", "send", "sentence", "september", "seven", "seventeen",
  "seventy", "share", "shopping", "short", "show", "sick", "similar", "singer", "sister", "sit",
  "situation", "six", "sixteen", "sixty", "skill", "skirt", "sleep", "slow", "small", "somebody",
  "someone", "something", "sometimes", "son", "soon", "sound", "soup", "south", "speak", "special",
  "spelling", "spend", "sport", "stand", "start", "statement", "stay", "still", "stop", "story",
  "street", "strong", "student", "study", "style", "subject", "success", "sugar", "sunday", "supermarket",
  "sure", "sweater", "swimming", "take", "talk", "tall", "taxi", "tea", "teach", "teacher",
  "teenager", "telephone", "television", "tell", "ten", "terrible", "test", "text", "thanks", "theatre",
  "thing", "think", "third", "thirsty", "thirteen", "thirty", "thousand", "three", "thursday", "time",
  "tired", "title", "together", "toilet", "tomato", "tooth", "topic", "tourist", "travel", "trousers",
  "true", "try", "tuesday", "turn", "tv", "twelve", "twenty", "twice", "two", "type",
  "umbrella", "uncle", "understand", "university", "upstairs", "us", "use", "useful", "usually", "vacation",
  "vegetable", "visit", "visitor", "wait", "waiter", "wake", "wall", "want", "wash", "way",
  "wear", "weather", "wednesday", "weekend", "welcome", "well", "west", "wife", "win", "wine",
  "without", "woman", "wonderful", "word", "work", "worker", "world", "write", "writer", "writing",
  "wrong", "yeah", "young",
];

/** Kid difficulty: words from the first KID_POOL_SIZE entries, at most this many letters. */
export const KID_MAX_WORD_LENGTH = 6;

export function getWordPool(isKidDifficulty) {
  if (isKidDifficulty) {
    return WORD_BANK.slice(0, KID_POOL_SIZE).filter((w) => w.length <= KID_MAX_WORD_LENGTH);
  }
  return WORD_BANK.slice(0, ADULT_POOL_SIZE);
}
