export const KID_POOL_SIZE = 200;
export const ADULT_POOL_SIZE = 500;
export const WORD_BANK = [
  "apple", "banana", "orange", "grape", "mango", "peach", "lemon", "melon", "berry", "pear",
  "cat", "dog", "bird", "fish", "frog", "duck", "lion", "tiger", "zebra", "horse",
  "cow", "goat", "sheep", "mouse", "rabbit", "monkey", "panda", "koala", "whale", "shark",
  "red", "blue", "green", "yellow", "gold", "purple", "pink", "brown", "black", "white",
  "sun", "moon", "star", "cloud", "rain", "snow", "wind", "storm", "sky", "light",
  "book", "pen", "pencil", "paper", "chair", "table", "clock", "phone", "bag", "shoe",
  "shirt", "pants", "socks", "hat", "coat", "dress", "bed", "door", "window", "house",
  "car", "bus", "train", "plane", "boat", "bike", "road", "park", "school", "store",
  "happy", "sad", "angry", "smile", "laugh", "jump", "run", "walk", "dance", "sing",
  "yes", "no", "hello", "thank", "please", "sorry", "water", "milk", "bread", "rice",
  "ant", "bee", "bug", "fly", "worm", "snake", "turtle", "owl", "eagle", "hawk",
  "crow", "swan", "goose", "hen", "rooster", "pig", "hamster", "guinea", "pet", "farm",
  "barn", "field", "river", "lake", "ocean", "beach", "sand", "shell", "coral", "reef",
  "island", "volcano", "forest", "tree", "leaf", "root", "seed", "flower", "grass", "weed",
  "bush", "vine", "oak", "pine", "maple", "cedar", "palm", "cactus", "desert", "oasis",
  "meadow", "valley", "canyon", "cliff", "cave", "hill", "mountain", "peak", "glacier", "ice",
  "frost", "dew", "mist", "fog", "steam", "heat", "cold", "warm", "cool", "breeze",
  "gust", "hurricane", "tornado", "earthquake", "thunder", "lightning", "bolt", "rainbow", "dawn", "dusk",
  "noon", "midnight", "evening", "morning", "afternoon", "tonight", "today", "tomorrow", "yesterday", "week",
  "month", "year", "season", "spring", "summer", "autumn", "winter", "holiday", "birthday", "party",
  "gift", "toy", "doll", "ball", "kite", "balloon", "puzzle", "block", "robot", "rocket",
  "alien", "planet", "comet", "meteor", "space", "astronaut", "pilot", "sailor", "captain", "pirate",
  "treasure", "map", "compass", "anchor", "harbor", "dock", "bridge", "tunnel", "station", "airport",
  "hotel", "museum", "library", "theater", "cinema", "music", "song", "drum", "flute", "guitar",
  "piano", "violin", "trumpet", "horn", "whistle", "bell", "alarm", "watch", "calendar", "diary",
  "letter", "stamp", "envelope", "package", "basket", "bucket", "bowl", "plate", "spoon", "fork",
  "knife", "cup", "mug", "bottle", "jar", "box", "pack", "suitcase", "wallet", "coin",
  "dollar", "cent", "price", "shop", "market", "mall", "bakery", "butcher", "cafe", "diner",
  "kitchen", "oven", "stove", "fridge", "freezer", "sink", "tap", "shower", "bath", "towel",
  "soap", "brush", "comb", "mirror", "lamp", "candle", "torch", "battery", "wire", "plug",
  "socket", "screen", "keyboard", "cable", "internet", "email", "website", "video", "photo", "camera",
  "picture", "frame", "statue", "painting", "canvas", "ink", "paint", "color", "crayon", "marker",
  "chalk", "board", "eraser", "ruler", "scissors", "tape", "glue", "paperclip", "staple", "pin",
  "needle", "thread", "button", "zipper", "pocket", "belt", "glove", "scarf", "ribbon", "lace",
  "wool", "cotton", "silk", "leather", "wood", "metal", "steel", "iron", "copper", "brass",
  "silver", "jewel", "ring", "necklace", "bracelet", "earring", "crown", "sword", "shield", "castle",
  "knight", "dragon", "wizard", "witch", "magic", "spell", "potion", "crystal", "maze", "labyrinth",
  "riddle", "trophy", "medal", "badge", "sticker", "tattoo", "seal", "sign", "symbol", "arrow",
  "circle", "square", "triangle", "diamond", "heart", "spade", "club", "chess", "checkers", "domino",
  "dice", "poker", "bingo", "lottery", "ticket", "coupon", "prize", "reward", "bonus", "level",
  "score", "record", "champion", "winner", "loser", "player", "team", "coach", "referee", "stadium",
  "arena", "gym", "yoga", "ballet", "karate", "judo", "boxing", "wrestling", "fencing", "archery",
  "bowling", "golf", "tennis", "soccer", "rugby", "hockey", "baseball", "cricket", "volleyball", "badminton",
  "squash", "racket", "net", "goal", "post", "jersey", "helmet", "pads", "uniform", "boots",
  "cleats", "skate", "ski", "sled", "surf", "dive", "swim", "float", "lifejacket", "sail",
  "mast", "oar", "paddle", "canoe", "kayak", "raft", "ferry", "cruise", "submarine", "tanker",
  "cargo", "truck", "van", "jeep", "wagon", "tractor", "bulldozer", "crane", "forklift", "elevator",
  "escalator", "subway", "tram", "cablecar", "monorail", "highway", "traffic", "signal", "crosswalk", "sidewalk",
  "alley", "avenue", "boulevard", "district", "neighborhood", "village", "town", "city", "capital", "province",
  "state", "nation", "border", "passport", "visa", "journey", "voyage", "trip", "tour", "guide",
];

export function getWordPool(isKidDifficulty) {
  if (isKidDifficulty) return WORD_BANK.slice(0, KID_POOL_SIZE);
  return WORD_BANK.slice(0, ADULT_POOL_SIZE);
}
